#:schema node_modules/wrangler/config-schema.json
name = "crud-example"
main = "src/index.js"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "crud_namespace", id = "b8fa01deb9d8454096e6dcfb07d2f41e" }
]

[vars]
DEBUG = "true"